version: '3'

services:
    
   postgres:
        image: 'postgres:11.1-alpine'
        env_file:
            - '.env'
        volumes:
            - 'postgres:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
    web:
        build: .
        env_file:
            - '.env'
        volumes:
            - 
        ports:
            - "5000:5000"
    
volumes:
    postgres: